# Set up and run this Streamlit App
import streamlit as st
from functions import worker1 
from functions.utility import check_password

# Check if the password is correct.  
if not check_password():  
    st.stop()

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="1 - SSS Policy Explainer"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Find Out More About The Silver Support Scheme")

form = st.form(key="form")
form.subheader("Enter your query below")

user_prompt = form.text_area("For example: What are the payment dates for the Silver Support Scheme?", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    response = worker1.process_user_query(user_prompt) # <--- This calls the helper function that we have created 🆕
    st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")


with st.expander("Disclaimer"):
    st.write("IMPORTANT NOTICE: This web application is a prototype developed for educational purposes only. The information provided here is NOT intended for real-world usage and should not be relied upon for making any decisions, especially those related to financial, legal, or healthcare matters. Furthermore, please be aware that the LLM may generate inaccurate or incorrect information. You assume full responsibility for how you use any generated output. Always consult with qualified professionals for accurate and personalized advice.")